language: node_js
node_js:
  - stable
  - 5.2
  - 4.2
  - 4.0
install:
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm run cover
after_success:
  - make docs
  - bash ./scripts/deploy_docs.sh
env:
  global:
  - secure: nKnBc6ux8wiQxcvmTfQxiVPhUWtc2ruEKPusDbMh+7hXGMEltw0AGjFZXfpOPA+ZyLDL+2RsmD4YxqQV4t+KdGe0DWOAd0VqX5tLfFw30QogABPBa2f5ittjbN4LI0C6mgIsTz+tt4vqgRgp+VMZtyUaYW6ucRa6CEJ/n3r3Ebrk3/eYMugOKPDJf60jdEKKM6KChO/RC7JxqEgk16/eVhmAzYG8x5OWEceCTZXa+AHPvobOzOKzM6rBHHwp7H7xsfl1Y7W4tgckuWzH530Rf1cIyK5L3NNegSwLSVDkWKS295QFSZNQvMz425ijhABkZdOJKOEKc6xKpKc6VTRPl0Vu5LmjOQ3dqgT4B1KOpMl8FtEhS8tHu5U1b2wnxvatXlC4uPRgHkpzaQVYIWtWvir/D7Ia4H7JHNE8Y7djZpNpqEeIfpeMo1EbMUC4oRg7lBlmjxn/04qSvNyylNzPwRBBR+sBfP6BjbMFEQZqPotNWGcBKykpsErkGYw8lNzwihMeDPhOjZE/gQv1XbdH0isTS+ApLLtaAK+82xcAdC+2Nx7S/8SaB+yAORjawnxImhVJaFq3bIXhSVHqTywhhMNE+BabG3WvtBxdAvlmA/Sz5swhABft3+j9oa2DcrXk8w5N2551UCqXipyT4q05ouRc1s9EzkwUo5d69yK4xRY=
