language: node_js
node_js:
  - stable
  - 5.2
install:
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run cover
after_success:
  - make docs
  - bash ./scripts/deploy_docs.sh
env:
  global:
  - secure: GjYkp+d/Sflp8n6B/BMWe8Tx61hz8eoT4ENnUEpEc1yWUpVhp7s841Q7ajuyTbqER4riDoa9qqGNaKkhYytetzAKFrhfpkAwsfy3kMNfiFPeFEvGNW2TB2aRxsFUwtOQ+WYQ92r27/vDDBq8dTqbuLs4+hl9xQcb00dAbJckgcAL6D9d1V6x9KaKxM0YA2UMEkE3M6vv08LLEXVwbPDj4oMq/cZ4F3CdKvdTT8wJlO5LIJyHxLY5ukBglGBWjS4iaAfTfaqK0o2UB/pz03aX2ZvO9gYpuVSBI7YoO0efeEAKiVoLeD6PCma+5LAAItHDDXoHIGtIFjdnuNL7v2LYSUXRTOzC0d4y2ESQc+nvm0268N5oOwHba9wMbzJvlVvkpH6nKDa7Gb4JZdKTVDqObwj4xoPifRmFHsbb6O4JMZEz27+fRIF2j6qYg+eAx6ZVdxTSHOVFAe8NlJIDaDoz+c5W9skTw09n7/+WwJLXlk/P7q8hqZkPag2A7gAolXd3tkmexXdj8TeMJkVuNVVqt/PvyImo/gr2AK+hoNlweJwW5A7zNfDzDzLmFw9tHwVhpFJbwbVFeH6q+JOoY5CRADG9BxA1TRanQtdzsgVIkOU+9VhBZgRRtoRoI92R2HMiq8bS3D5b6nol3LcR1XJytK3dUH2i3OXAk/cQ9wLBAvc=